openapi: 3.0.0
info:
  title: Mon Cheptel API
  version: 1.0.0
  description: API pour gérer son cheptel

servers:
  - url: https://mon-cheptel.vincentmagnien.com/api/v1
    description: Production
  - url: http://localhost:3000/api/v1
    description: Development

paths:

components:
  schemas:
