services:
  app:
    image: ghcr.io/vincmgn/mon-cheptel:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NUXT_SECRET: ${NUXT_SECRET}
    networks:
      - traefik
      - mon-cheptel
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mon-cheptel.rule=Host(`mon-cheptel.vincentmagnien.com`)'
      - 'traefik.http.routers.mon-cheptel.entrypoints=websecure'
      - 'traefik.http.services.mon-cheptel.loadbalancer.server.port=3000'
      - 'traefik.http.routers.mon-cheptel.tls.certresolver=letsencryptresolver'

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user_prod
      POSTGRES_PASSWORD: password_prod
      POSTGRES_DB: cheptel_db
    volumes:
      - pg_prod_data:/var/lib/postgresql/data
    networks:
      - mon-cheptel
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user_prod -d cheptel_db']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_prod_data:

networks:
  mon-cheptel:
  traefik:
    external: true
