name: Manual Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Type de version (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Requis pour pousser le commit et le tag

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Nécessaire pour les tags et l'historique complet

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump version, Commit and Tag
        run: |
          # npm version modifie le package.json, crée le commit et le tag git
          npm version ${{ github.event.inputs.bump }} -m "chore: release v%s"

      - name: Push changes and tags
        run: |
          git push origin main
          git push origin --tags
